# Site settings
title: steebe
email: steve@stevebass.me
description: >- # this means to ignore newlines until "baseurl:"
  A site for the people, to learn about Steve and the stuff he's learned.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SteveBass
github_username:  steebe

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Environment
timezone: America/New_York

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
    - _posts/2018-06-30-welcome-to-jekyll.markdown
    - _posts/2018-11-13-apple.markdown
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
